daysUntilStale: 60
daysUntilClose: 15
exemptLabels:
  - pinned
  - security
staleLabel: wontfix
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. If you have any question, please contact me directly at thedaviddias@gmail.com. Thank you
  for your contributions to that project!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
