# env:
#   global:
#     - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c
language: node_js
sudo: false
node_js:
  - "4.1"
  - "4.0"
install:
  - npm install
script:
  - gulp test
after_script:
  - gulp build
#   - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications: # set notification options
  email:
    recipients:
      - thedaviddias@gmail.com
branches:
  only:
    - gh-pages
